### ISSUE TITLE
`$formPage->notificationEmail_from()` is missing?

### ISSUE THREAD

**Issue by n-kort** [arnoson/kirby-forms#11]
Is there some other configuration for this? Enabling the notification email just throws an error on form submit, if I manually add a `Notificationemail-from` key in the form's content file it works.

**Comment by arnoson** [comment]
Just tested it and you are right, good catch! I'll add a field to the form blueprint

**Comment by arnoson** [comment]
Should be fixed in [v0.2.3](https://github.com/arnoson/kirby-forms/releases/tag/v0.2.3), let me know if everything works for you as expected
